#ifndef SPACESHIPGAMECONFIG_H_
#define SPACESHIPGAMECONFIG_H_


#define F_TIMER F_CPU / 8

#define SHIP_BODY_SIZE 4
#define MAX_NR_BULLETS_PER_SHIP 20

#define MAX_NR_ENEMIES 		5
#define INITIAL_NR_ENEMIES	3

#define ENEMIES_DODGE_UPDATE_TIMEOUT    500
#define BULLETS_UPDATE_TIMEOUT          75

#define PLAYER_MAX_HP 200
#define PLAYER_BASE_FIRE_RATE 2.0f
#define PLAYER_INIT_POS (vec2_t){3, 14}

#define ENEMY_MAX_HP 3
#define ENEMY_BASE_FIRE_RATE 1.0f

#endif /* SPACESHIPGAMECONFIG_H_ */